import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cards-container',
  templateUrl: './cards-container.component.html',
  styleUrls: ['./cards-container.component.scss'],
})
export class CardsContainerComponent implements OnInit {
  parentArr: any = [
    {
      name: 'Eman',
      lastName: 'Tantawy',
      specialty: 'Ph.D. and Consultant Oral and Maxillofacial Surgery',
      visitors: 402,
      moreInfo:
        'Dentist Specialized in Cosmetic Dentistry, Oral Radiology, Elder Dentistry and Pediatric Dentistry',
      country: 'El-Mohandessin',
      city: 'Gezziret El Arab',
      fees: 200,
      waitTime: 14,
      i: 1,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Ghada',
      lastName: 'Yehya',
      specialty: 'Dental Esthetic Specialist',
      visitors: 80,
      moreInfo:
        'Dentist Specialized in Pediatric Dentistry, Implantology, Endodontics and Orthodontics',
      country: 'El-Obour City',
      city: 'elthqafa street',
      fees: 100,
      waitTime: 35,
      i: 2,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Ahmed',
      lastName: 'Badrr',
      specialty: 'Specialist of Dentistry - Badr Dental Center',
      visitors: 158,
      moreInfo:
        'Dentist Specialized in Adult Dentistry, Elder Dentistry, Oral and Maxillofacial Surgery and Pediatric Dentistry',
      country: 'El-Mansoura',
      city: 'Hay El Gamaa Gehahan St',
      fees: 100,
      waitTime: 10,
      i: 3,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Ali',
      lastName: 'Eltahan',
      specialty: 'Masters of Endodontics , Mastership Of Laser Therapy in Dentistry',
      visitors: 117,
      moreInfo: 'Dentist Specialized in Elder Dentistry, Oral Radiology, Pediatric Dentistry and Adult Dentistry',
      country: 'El-Zagazig',
      city: 'Taba street',
      fees: 100,
      waitTime: 12,
      i: 4,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Passent',
      lastName: 'Ahmed',
      specialty: 'Dentist',
      visitors: 33,
      moreInfo: 'Dentist Specialized in Endodontics, Adult Dentistry, Cosmetic Dentistry and Pediatric Dentistry',
      country: 'Sporting',
      city: 'port Said St',
      fees: 150,
      waitTime: 9,
      i: 5,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Mohamed',
      lastName: 'Elhadidy',
      specialty: 'Implant Ortho Specialist',
      visitors: 153,
      moreInfo: 'Dentist Specialized in Oral and Maxillofacial Surgery, Endodontics, Cosmetic Dentistry and Implantology',
      country: 'El-Rehab',
      city: 'sadat axis',
      fees: 250,
      waitTime: 11,
      i: 6,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Selim',
      lastName: 'Gouda',
      specialty: 'DDs, MSc in Implant Dentistry, Frankfurt- Germany.',
      visitors: 218,
      moreInfo: 'Dentist Specialized in Implantology, Cosmetic Dentistry, Endodontics and Elder Dentistry',
      country: 'San Stefano',
      city: 'Sanstefano Grand Plaza',
      fees: 200,
      waitTime: 10,
      i: 7,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
    {
      name: 'Hanaa',
      lastName: 'Fouad',
      specialty: 'Consultant of Endodontics, Prosthodontics and Implantology, Master of Endodontics',
      visitors: 250,
      moreInfo: 'Dentist Specialized in Pediatric Dentistry, Implantology, Cosmetic Dentistry and Endodontics',
      country: 'El-Maadi',
      city: 'Street 9-At the Junction of hassanien Eldesouki Street',
      fees: 100,
      waitTime: 29,
      i: 8,
      days: [' Wed ', ' Tus ', ' Sun '],
    },
  ];
  constructor() {}

  ngOnInit(): void {}
}
